name: Release
on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Semantic Release
          uses: cycjimmy/semantic-release-action@v2
          id: semantic
          with:
            extra_plugins: |
              @semantic-release/changelog
              @semantic-release/git
              conventional-changelog-eslint
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}